# Generated by Django 3.2.2 on 2021-06-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=64)),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('d', models.IntegerField()),
                ('e', models.IntegerField()),
                ('f', models.IntegerField()),
                ('g', models.IntegerField()),
                ('h', models.IntegerField()),
                ('i', models.IntegerField()),
                ('j', models.IntegerField()),
                ('k', models.IntegerField()),
                ('l', models.IntegerField()),
                ('m', models.IntegerField()),
                ('n', models.IntegerField()),
                ('o', models.IntegerField()),
                ('p', models.IntegerField()),
                ('q', models.IntegerField()),
                ('r', models.IntegerField()),
                ('s', models.IntegerField()),
            ],
        ),
    ]
